# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-01 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('sampleColumnName', models.CharField(max_length=255)),
                ('blockColumnName', models.CharField(blank=True, max_length=255, null=True)),
                ('logFoldChangeDecideTests', models.FloatField(blank=True, null=True)),
                ('pValueCutOffDecideTests', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('plotPath', models.CharField(max_length=255)),
                ('plotFileName', models.CharField(max_length=128)),
                ('analysisDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.AnalysisDetail')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('filePath', models.CharField(max_length=255)),
                ('resultFileName', models.CharField(max_length=128)),
                ('analysisDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.AnalysisDetail')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('uploadedDate', models.DateTimeField(blank=True, null=True)),
                ('filePath', models.CharField(max_length=512)),
                ('startingColumn', models.IntegerField(blank=True, null=True)),
                ('commaOrTabDelimitedFlag', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DesignFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('baseLineFactorValue', models.CharField(max_length=255)),
                ('analysisDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.AnalysisDetail')),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimmaContrast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('numerator', models.CharField(max_length=128)),
                ('denominator', models.CharField(max_length=128)),
                ('analysisDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.AnalysisDetail')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('autoLoaded', models.NullBooleanField()),
                ('autoLoadedFromPath', models.CharField(blank=True, max_length=512, null=True)),
                ('autoLoadedDate', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleName', models.CharField(max_length=512)),
                ('numberOfInputReads', models.IntegerField()),
                ('pctUniquelyMappedReads', models.FloatField()),
                ('pctMappedMultipleLoci', models.FloatField()),
                ('pctUnMappedTooManyLoci', models.FloatField()),
                ('pctUnMappedTooManyMismatches', models.FloatField()),
                ('pctUnMappedTooShort', models.FloatField()),
                ('pctUnMappedOther', models.FloatField()),
                ('qcQualiMapHTMLPath', models.CharField(max_length=512)),
                ('fastQcHTMLPath', models.CharField(max_length=512)),
                ('totalAlignments', models.IntegerField()),
                ('dataFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.DataFile')),
            ],
        ),
        migrations.CreateModel(
            name='SampleNameXRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFileColumnName', models.CharField(blank=True, max_length=255, null=True)),
                ('sampleName', models.CharField(blank=True, max_length=255, null=True)),
                ('analysisDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.AnalysisDetail')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('submittedOn', models.DateTimeField(blank=True, null=True)),
                ('downloadDataFileLink', models.CharField(blank=True, max_length=512, null=True)),
                ('completedTime', models.DateTimeField(blank=True, null=True)),
                ('analysisDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rnaseq.AnalysisDetail')),
                ('jobStatusCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.JobStatusCode')),
                ('submittedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='submittedjob',
            name='submittedJobType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.SubmittedJobType'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='fileType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rnaseq.FileType'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.Project'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='uploadedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='dataFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnaseq.DataFile'),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='normalizationMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rnaseq.NormalizationMethod'),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='phenotypeFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenotypeFile', to='rnaseq.DataFile'),
        ),
    ]
