FOLD_CHANGE_UPPER_CUT_OFF = 1.5
FOLD_CHANGE_LOWER_CUT_OFF = 1.5
P_VALUE_CUT_OFF = 0.05
NUM_COMPARISONS = 4

VOXEL_SPACE_DIM_1 = 67
VOXEL_SPACE_DIM_2 = 41
VOXEL_SPACE_DIM_3 = 58

DEFAULT_NUM_RECORDS_TO_DISPLAY = 500

NUM_ROWS_PER_FETCH = 2000

DECIDE_TESTS_LFC = 0.585

DECIDE_TESTS_PVALUE = 0.05

DEFAULT_MAX_LIST_DISPLAY = 500

DEFAULT_STARTING_COLUMN = 6

